package com.example.admindiyabatti.utils

import com.example.admindiyabatti.R

object Constants {

      val allProductsCategory = arrayOf(
        "Baby care ",
        "Vegetable & Fruits ",
        "Dairy & Breakfast",
        "Munchies",
        "Cold Drinks",
        "Instant & Frozen Food",
        "Tea Coffer & Health Drinks",
        "Bakery & Biscuits",
        "Sweet Tooth",
        "Atta Rice & Dal",
        "Dry Fruits Masala & Oil",
        "Sauces & Spreads",
        "Chicken Meat & Fish",
        "Pan Corner",
        "Organic & Premium",
        "Baby Care",
        "Pharma & Wellness",
        "Cleaning Essential",
        "Home & Office",
        "Personal Care",
        "Pet Care",
        "Bakery & Biscuits",
        "Sweet Tooth",
        "Atta Rice & Dal",
        "Dry Fruits Masala & Oil",
        "Sauces & Spreads",
        "Chicken Meat & Fish",
        "Pan Corner",
        "Organic & Premium",
        "Baby Care",
        "Pharma & Wellness",
        "Cleaning Essential",
        "Home & Office",
        "Personal Care",
        "Pet Care",
    )
    val allProductsCategoryIcon = arrayOf(
        R.drawable.baby,
        R.drawable.vegetable,
        R.drawable.dairy_breakfast,
        R.drawable.munchies,
        R.drawable.cold_and_juices,
        R.drawable.instant_frozen,
        R.drawable.tea_coffee,
        R.drawable.bakery_biscuits,
        R.drawable.sweet_tooth,
        R.drawable.atta_rice,
        R.drawable.dry_masala,
        R.drawable.sauce_spreads,
        R.drawable.chicken_meat,
        R.drawable.paan_corner,
        R.drawable.organic_premium,
        R.drawable.baby_care,
        R.drawable.pharma_wellness,
        R.drawable.cleaning,
        R.drawable.home_office,
        R.drawable.personal_care,
        R.drawable.pet_care,
        R.drawable.bakery_biscuits,
        R.drawable.sweet_tooth,
        R.drawable.atta_rice,
        R.drawable.dry_masala,
        R.drawable.sauce_spreads,
        R.drawable.chicken_meat,
        R.drawable.paan_corner,
        R.drawable.organic_premium,
        R.drawable.baby_care,
        R.drawable.pharma_wellness,
        R.drawable.cleaning,
        R.drawable.home_office,
        R.drawable.personal_care,
        R.drawable.pet_care,
    )
    val allUnitsOfProducts = arrayOf(
        "kg",
        "gm",
        "ml",
        "Ltr",
        "packets",
        "places",

        )

    val allProductType = arrayOf(
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",
        "Holi diya",
        "Diwali diya",

        )



}